import { Button } from "@/components/ui/button";
import { Activity, ArrowUpRight, Cpu, Database, Plus } from "lucide-react";

export function CommandDeck({ onNewConversation }: { onNewConversation: () => void }) {
  return <section className="command-deck min-h-[55vh] overflow-hidden"><div className="command-deck-grid" /><div className="command-deck-glow" /><div className="relative z-10 grid gap-7 p-5 sm:p-8 xl:grid-cols-[1.35fr_.65fr]"><div className="flex flex-col justify-between"><div><div className="flex items-center gap-2 font-mono text-[10px] tracking-[0.18em] text-cyan-200"><span className="live-dot" />SISTEMA PRONTO PARA INFERÊNCIA</div><h2 className="glitch-title mt-5 max-w-2xl text-4xl font-black leading-[.88] sm:text-6xl">CONSTRUA A PRÓXIMA LINHA DE PENSAMENTO.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-zinc-300 sm:text-base">Inicie um canal, escolha uma ferramenta autorizada ou use memória contextual para transformar uma instrução em fluxo de trabalho.</p></div><div className="mt-9 flex flex-wrap gap-3"><Button onClick={onNewConversation} className="system-button h-11 px-5"><Plus className="mr-2 size-4" />INICIAR CANAL <ArrowUpRight className="ml-3 size-4" /></Button><div className="command-key"><span>⌘</span> NOVA CONVERSA</div></div></div><div className="space-y-3"><div className="telemetry-card telemetry-card-main"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] tracking-[0.16em] text-cyan-300">[NÓ DE EXECUÇÃO]</p><p className="mt-3 font-mono text-2xl text-zinc-100">LOCAL//01</p></div><Cpu className="size-5 text-fuchsia-300" /></div><div className="signal-bars mt-7"><i /><i /><i /><i /><i /><i /><i /><i /></div><p className="mt-3 font-mono text-[10px] text-zinc-500">OLLAMA_LINK: STANDBY</p></div><div className="grid grid-cols-2 gap-3"><Telemetry icon={Database} label="MEMÓRIA" value="ARMADA" /><Telemetry icon={Activity} label="CANAL" value="IDLE" /></div><div className="border border-white/10 bg-black/25 p-4"><p className="font-mono text-[10px] tracking-[0.16em] text-zinc-500">[SEQUÊNCIA RÁPIDA]</p><ol className="mt-3 space-y-2 font-mono text-[11px] leading-5 text-zinc-300"><li><span className="text-cyan-300">01</span> Criar conversa</li><li><span className="text-cyan-300">02</span> Enviar instrução</li><li><span className="text-cyan-300">03</span> Acionar ferramentas</li></ol></div></div></div></section>;
}

function Telemetry({ icon: Icon, label, value }: { icon: typeof Database; label: string; value: string }) {
  return <div className="telemetry-card"><Icon className="size-4 text-cyan-300" /><p className="mt-4 font-mono text-[10px] tracking-[0.12em] text-zinc-500">{label}</p><p className="mt-1 font-mono text-sm text-zinc-100">{value}</p></div>;
}
